# Generated by Django 5.0 on 2023-12-07 12:54

import player.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('preview_file', models.ImageField(upload_to=player.models.preview_directory_path)),
                ('video_file', models.FileField(upload_to=player.models.video_directory_path)),
                ('views', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['pk', 'title', 'created_at', 'views'],
            },
        ),
    ]
